name: thunder_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  web3auth_flutter: ^1.3.0
  ethers: ^0.0.1+3
  flutter_secure_storage: ^8.0.0
  web3dart: ^2.6.1
  smooth_page_indicator: ^1.1.0
  web_socket_channel: ^2.4.0
  animated_text_kit: ^4.2.1
  eth_sig_util: ^0.0.9
  flutter_web3: ^2.1.9
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  intl: ^0.18.1
  audioplayers: ^4.1.0
  share: ^2.0.1
  url_launcher: ^6.0.9
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  flutter_local_notifications: ^15.1.0+1
  flutter_dynamic_icon: ^2.1.0
  uni_links: ^0.5.1
  app_links: ^3.4.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lottie: ^2.3.2

flutter:
  uses-material-design: true
  assets:
      - contracts/build/contracts/Registry.json
      - contracts/build/contracts/MinimalForwarder.json
      - contracts/build/contracts/ThunderChatProfileContract.json
      - contracts/build/contracts/ThunderChatMessageContract.json
      - artifacts/contracts/ThunderChatMessageContract.sol/ThunderChatMessageContract.json
      - assets/audio/
      - assets\thunder_logo.png
      - assets\login-facebook.svg
      - assets\login-google.svg
      - assets\login-twitter.svg
      - assets\blockchain-animation.json
      - assets\encryption-animation.json
      - assets\privacy-animation.json
      - assets\aa-animation.json
